[default]
frontend_urls = ["http://localhost:19429"]

[default.mongodb]
url = "mongodb://localhost:27017"
db = "pkgdash"

[default.clickhouse]
url = "http://localhost:8123"
db = "gharchive"
user = "default"
password = ""
