/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlertItem: typeof import('./components/AlertItem.vue')['default']
    BarChartCard: typeof import('./components/BarChartCard.vue')['default']
    BigStatsCard: typeof import('./components/BigStatsCard.vue')['default']
    BottomPart: typeof import('./components/BottomPart.vue')['default']
    DataCard: typeof import('./components/DataCard.vue')['default']
    DependencyView: typeof import('./components/DependencyView.vue')['default']
    ExpandMoreCard: typeof import('./components/ExpandMoreCard.vue')['default']
    GradientBg: typeof import('./components/GradientBg.vue')['default']
    Graph: typeof import('./components/Graph.vue')['default']
    PackageCard: typeof import('./components/PackageCard.vue')['default']
    PackageView: typeof import('./components/PackageView.vue')['default']
    README: typeof import('./components/README.md')['default']
    RepositoryView: typeof import('./components/RepositoryView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./components/StatsCard.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    Waves: typeof import('./components/Waves.vue')['default']
  }
}
